flowchart TD
    examples_basic["examples.basic<br/>32 funcs"]
    examples_fastapi_docker["examples.fastapi-docker<br/>23 funcs"]
    examples_text2fraq["examples.text2fraq<br/>27 funcs"]
    examples_v030["examples.v030<br/>4 funcs"]
    fraq_adapters["fraq.adapters<br/>54 funcs"]
    fraq_cli["fraq.cli<br/>18 funcs"]
    fraq_core["fraq.core<br/>17 funcs"]
    fraq_formats["fraq.formats<br/>14 funcs"]
    fraq_generators["fraq.generators<br/>9 funcs"]
    fraq_query["fraq.query<br/>12 funcs"]
    fraq_schema_export["fraq.schema_export<br/>7 funcs"]
    fraq_server["fraq.server<br/>7 funcs"]
    fraq_streaming["fraq.streaming<br/>5 funcs"]
    fraq_text2fraq["fraq.text2fraq<br/>46 funcs"]
    examples_text2fraq ==>|10| fraq_schema_export
    examples_text2fraq ==>|7| fraq_text2fraq
    fraq_cli ==>|6| fraq_formats
    fraq_adapters ==>|6| fraq_formats
    examples_fastapi_docker ==>|4| fraq_formats
    examples_basic ==>|4| fraq_streaming
    examples_basic ==>|4| fraq_query
    examples_basic -->|2| fraq_schema_export
    examples_basic -->|2| fraq_formats
    fraq_generators -->|1| fraq_core
    fraq_cli -->|1| fraq_text2fraq
    fraq_query -->|1| fraq_formats
    examples_fastapi_docker -->|1| fraq_text2fraq
    examples_fastapi_docker -->|1| fraq_streaming
    fraq_text2fraq -->|1| fraq_formats
    examples_v030 -->|1| fraq_text2fraq
    fraq_server -->|1| fraq_text2fraq
